# Generated by Django 3.2.5 on 2022-06-28 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemid', models.CharField(max_length=50, verbose_name='ID')),
                ('problemname', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=300)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputdoc', models.CharField(max_length=500)),
                ('outputdoc', models.CharField(max_length=500)),
                ('problemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answercode', models.CharField(max_length=300)),
                ('submissiontime', models.TimeField(default=django.utils.timezone.now)),
                ('verdict', models.CharField(max_length=20)),
                ('problemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.problem')),
            ],
        ),
    ]
