# Generated by Django 3.2.5 on 2022-06-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testcases',
            new_name='Testcase',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
